In [2]:
import bz2
import pandas as pd

In [3]:
import numpy as np

In [41]:
d = bz2.open('1987.csv.bz2')

In [42]:
df = pd.read_csv(d)
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1987,10,14,3,741.0,730,912.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1987,10,15,4,729.0,730,903.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1987,10,17,6,741.0,730,918.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1987,10,18,7,729.0,730,847.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1987,10,19,1,749.0,730,922.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [80]:
len(df)

1311826

In [81]:
#### DO NOT RERUN ABOVE THIS LINE

#### create small df

In [82]:
df_small = df[df['Month'] == 10]

In [83]:
df_small.head(4).T

                       0      1      2      3
Year                1987   1987   1987   1987
Month                 10     10     10     10
DayofMonth            14     15     17     18
DayOfWeek              3      4      6      7
DepTime            741.0  729.0  741.0  729.0
CRSDepTime           730    730    730    730
ArrTime            912.0  903.0  918.0  847.0
CRSArrTime           849    849    849    849
UniqueCarrier         PS     PS     PS     PS
FlightNum           1451   1451   1451   1451
TailNum              NaN    NaN    NaN    NaN
ActualElapsedTime   91.0   94.0   97.0   78.0
CRSElapsedTime        79     79     79     79
AirTime              NaN    NaN    NaN    NaN
ArrDelay            23.0   14.0   29.0   -2.0
DepDelay            11.0   -1.0   11.0   -1.0
Origin               SAN    SAN    SAN    SAN
Dest                 SFO    SFO    SFO    SFO
Distance           447.0  447.0  447.0  447.0
TaxiIn               NaN    NaN    NaN    NaN
TaxiOut              NaN    NaN    NaN    NaN
Cancelled              0      0      0      0
CancellationCode     NaN    NaN    NaN    NaN
Diverted               0      0      0      0
CarrierDelay         NaN    NaN    NaN    NaN
WeatherDelay         NaN    NaN    NaN    NaN
NASDelay             NaN    NaN    NaN    NaN
SecurityDelay        NaN    NaN    NaN    NaN
LateAircraftDelay    NaN    NaN    NaN    NaN

In [84]:
len(df_small)

448620

In [85]:
#df_small['OnTime'] = [1 if x <= 30 else 0 for x in df_small['ArrDelay']]
#df_small['Delayed'] = [1 if (x > 30 and x <= 60) else 0 for x in df_small['ArrDelay']]
#df_small['VeryDelayed'] = [1 if x > 60 else 0 for x in df_small['ArrDelay']]

In [86]:
df_small.head(6).T

                       0      1      2      3      4      5
Year                1987   1987   1987   1987   1987   1987
Month                 10     10     10     10     10     10
DayofMonth            14     15     17     18     19     21
DayOfWeek              3      4      6      7      1      3
DepTime            741.0  729.0  741.0  729.0  749.0  728.0
CRSDepTime           730    730    730    730    730    730
ArrTime            912.0  903.0  918.0  847.0  922.0  848.0
CRSArrTime           849    849    849    849    849    849
UniqueCarrier         PS     PS     PS     PS     PS     PS
FlightNum           1451   1451   1451   1451   1451   1451
TailNum              NaN    NaN    NaN    NaN    NaN    NaN
ActualElapsedTime   91.0   94.0   97.0   78.0   93.0   80.0
CRSElapsedTime        79     79     79     79     79     79
AirTime              NaN    NaN    NaN    NaN    NaN    NaN
ArrDelay            23.0   14.0   29.0   -2.0   33.0   -1.0
DepDelay            11.0   -1.0   11.0   -1.0   19.0   -2.0
Origin               SAN    SAN    SAN    SAN    SAN    SAN
Dest                 SFO    SFO    SFO    SFO    SFO    SFO
Distance           447.0  447.0  447.0  447.0  447.0  447.0
TaxiIn               NaN    NaN    NaN    NaN    NaN    NaN
TaxiOut              NaN    NaN    NaN    NaN    NaN    NaN
Cancelled              0      0      0      0      0      0
CancellationCode     NaN    NaN    NaN    NaN    NaN    NaN
Diverted               0      0      0      0      0      0
CarrierDelay         NaN    NaN    NaN    NaN    NaN    NaN
WeatherDelay         NaN    NaN    NaN    NaN    NaN    NaN
NASDelay             NaN    NaN    NaN    NaN    NaN    NaN
SecurityDelay        NaN    NaN    NaN    NaN    NaN    NaN
LateAircraftDelay    NaN    NaN    NaN    NaN    NaN    NaN

In [87]:
#df_small2 = df_small.drop(columns=['OnTime','Delayed','VeryDelayed'],axis=1)
#df_small2.head()

In [88]:
# create a list of our conditions
conditions = [
    (df_small['ArrDelay'] <= 30),
    (df_small['ArrDelay'] > 30) & (df_small['ArrDelay'] <= 60),
    (df_small['ArrDelay'] > 60),
    (df_small['Cancelled'] == 0)]

# create a list of the values we want to assign for each condition
values = [1, 2, 3, 0]

# create a new column and use np.select to assign values to it using our lists as arguments
df_small['DelayedTier'] = np.select(conditions, values)

# display updated DataFrame
df_small.head()

<ipython-input-88-26f0d19430df>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_small['DelayedTier'] = np.select(conditions, values)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,DelayedTier
0,1987,10,14,3,741.0,730,912.0,849,PS,1451,...,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1
1,1987,10,15,4,729.0,730,903.0,849,PS,1451,...,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1
2,1987,10,17,6,741.0,730,918.0,849,PS,1451,...,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1
3,1987,10,18,7,729.0,730,847.0,849,PS,1451,...,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,1
4,1987,10,19,1,749.0,730,922.0,849,PS,1451,...,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,2

In [89]:
## We have one column that we want to predict/classify.d

In [90]:
df_small.head(15).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
Year,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987
Month,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
DayofMonth,14,15,17,18,19,21,22,23,24,25,26,28,29,31,1
DayOfWeek,3,4,6,7,1,3,4,5,6,7,1,3,4,6,4
DepTime,741.0,729.0,741.0,729.0,749.0,728.0,728.0,731.0,744.0,729.0,735.0,741.0,742.0,726.0,936.0
CRSDepTime,730,730,730,730,730,730,730,730,730,730,730,725,725,725,915
ArrTime,912.0,903.0,918.0,847.0,922.0,848.0,852.0,902.0,908.0,851.0,904.0,919.0,906.0,848.0,1035.0
CRSArrTime,849,849,849,849,849,849,849,849,849,849,849,855,855,855,1001
UniqueCarrier,PS,PS,PS,PS,PS,PS,PS,PS,PS,PS,PS,PS,PS,PS,PS
FlightNum,1451,1451,1451,1451,1451,1451,1451,1451,1451,1451,1451,1451,1451,1451,1451
TailNum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ActualElapsedTime,91.0,94.0,97.0,78.0,93.0,80.0,84.0,91.0,84.0,82.0,89.0,98.0,84.0,82.0,59.0
CRSElapsedTime,79,79,79,79,79,79,79,79,79,79,79,90,90,90,46
AirTime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ArrDelay,23.0,14.0,29.0,-2.0,33.0,-1.0,3.0,13.0,19.0,2.0,15.0,24.0,11.0,-7.0,34.0
DepDelay,11.0,-1.0,11.0,-1.0,19.0,-2.0,-2.0,1.0,14.0,-1.0,5.0,16.0,17.0,1.0,21.0
Origin,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SAN,SFO
Dest,SFO,SFO,SFO,SFO,SFO,SFO,SFO,SFO,SFO,SFO,SFO,SFO,SFO,SFO,RNO
Distance,447.0,447.0,447.0,447.0,447.0,447.0,447.0,447.0,447.0,447.0,447.0,447.0,447.0,447.0,192.0
TaxiIn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TaxiOut,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cancelled,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CancellationCode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Diverted,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
CarrierDelay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WeatherDelay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NASDelay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SecurityDelay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LateAircraftDelay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DelayedTier,1,1,1,1,2,1,1,1,1,1,1,1,1,1,2

In [91]:
df_small['UniqueCarrier'].unique()

array(['PS', 'TW', 'UA', 'WN', 'EA', 'HP', 'NW', 'PA (1)', 'PI', 'CO',
       'DL', 'AA', 'US', 'AS'], dtype=object)

In [92]:
df_small2_drop = df_small.drop(columns=['TailNum',
                                        'AirTime',
                                        'Distance',
                                       'TaxiIn',
                                       'TaxiOut',
                                       'CancellationCode',
                                       'CarrierDelay','WeatherDelay',
                                       'NASDelay','SecurityDelay',
                                       'LateAircraftDelay'], axis=1)

In [93]:
df_small2_drop.head(3).T

                       0      1      2
Year                1987   1987   1987
Month                 10     10     10
DayofMonth            14     15     17
DayOfWeek              3      4      6
DepTime            741.0  729.0  741.0
CRSDepTime           730    730    730
ArrTime            912.0  903.0  918.0
CRSArrTime           849    849    849
UniqueCarrier         PS     PS     PS
FlightNum           1451   1451   1451
ActualElapsedTime   91.0   94.0   97.0
CRSElapsedTime        79     79     79
ArrDelay            23.0   14.0   29.0
DepDelay            11.0   -1.0   11.0
Origin               SAN    SAN    SAN
Dest                 SFO    SFO    SFO
Cancelled              0      0      0
Diverted               0      0      0
DelayedTier            1      1      1

In [94]:
df_small2_drop['UniqueCarrier'].unique()

array(['PS', 'TW', 'UA', 'WN', 'EA', 'HP', 'NW', 'PA (1)', 'PI', 'CO',
       'DL', 'AA', 'US', 'AS'], dtype=object)

In [95]:
# Replace the UniqueCarrier columns to integers so it can be used in RandomForest


mydict = {"PS" : 1, "TW" : 2, "UA": 3, "WN" : 4, "EA": 5,
         'HP': 6,
         'NW':7,
         'PA (1)':8,
         'PI':9,
         'CO':10,
         'DL':11,
         'AA':12,
         'US':13,
         'AS':14}
df3=df_small2_drop.replace({"UniqueCarrier": mydict})

In [96]:
df3.head(8).T

                       0      1      2      3      4      5      6      7
Year                1987   1987   1987   1987   1987   1987   1987   1987
Month                 10     10     10     10     10     10     10     10
DayofMonth            14     15     17     18     19     21     22     23
DayOfWeek              3      4      6      7      1      3      4      5
DepTime            741.0  729.0  741.0  729.0  749.0  728.0  728.0  731.0
CRSDepTime           730    730    730    730    730    730    730    730
ArrTime            912.0  903.0  918.0  847.0  922.0  848.0  852.0  902.0
CRSArrTime           849    849    849    849    849    849    849    849
UniqueCarrier          1      1      1      1      1      1      1      1
FlightNum           1451   1451   1451   1451   1451   1451   1451   1451
ActualElapsedTime   91.0   94.0   97.0   78.0   93.0   80.0   84.0   91.0
CRSElapsedTime        79     79     79     79     79     79     79     79
ArrDelay            23.0   14.0   29.0   -2.0   33.0   -1.0    3.0   13.0
DepDelay            11.0   -1.0   11.0   -1.0   19.0   -2.0   -2.0    1.0
Origin               SAN    SAN    SAN    SAN    SAN    SAN    SAN    SAN
Dest                 SFO    SFO    SFO    SFO    SFO    SFO    SFO    SFO
Cancelled              0      0      0      0      0      0      0      0
Diverted               0      0      0      0      0      0      0      0
DelayedTier            1      1      1      1      2      1      1      1

In [97]:
df3 = df3.drop(columns=['Origin','Dest','ArrDelay'],axis=1)

In [98]:
len(df3)

448620

In [99]:
df4 = df3.dropna()

In [100]:
len(df4)

444780

In [101]:
df4.head(2)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,ActualElapsedTime,CRSElapsedTime,DepDelay,Cancelled,Diverted,DelayedTier
0,1987,10,14,3,741.0,730,912.0,849,1,1451,91.0,79,11.0,0,0,1
1,1987,10,15,4,729.0,730,903.0,849,1,1451,94.0,79,-1.0,0,0,1

In [102]:
# Use numpy to convert to arrays
import numpy as np
# Labels are the values we want to predict
labels = np.array(df4['DelayedTier'])

In [103]:
# Remove the labels from the features
features= df4.drop(columns=['DelayedTier','UniqueCarrier'], axis = 1)

In [104]:
features.head(3)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,CRSElapsedTime,DepDelay,Cancelled,Diverted
0,1987,10,14,3,741.0,730,912.0,849,1451,91.0,79,11.0,0,0
1,1987,10,15,4,729.0,730,903.0,849,1451,94.0,79,-1.0,0,0
2,1987,10,17,6,741.0,730,918.0,849,1451,97.0,79,11.0,0,0

In [105]:
# Saving feature names for later use
feature_list = list(features.columns)

# Convert to numpy array
features = np.array(features)

In [106]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split

In [107]:
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, 
                               random_state = 42)

In [108]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (333585, 14)
Training Labels Shape: (333585,)
Testing Features Shape: (111195, 14)
Testing Labels Shape: (111195,)

In [109]:
feature_list

['Year',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'DepTime',
 'CRSDepTime',
 'ArrTime',
 'CRSArrTime',
 'FlightNum',
 'ActualElapsedTime',
 'CRSElapsedTime',
 'DepDelay',
 'Cancelled',
 'Diverted']

In [110]:
##Baseline Prediction

In [111]:
# The baseline predictions are the historical averages
#baseline_preds = test_features[:, feature_list.index('average')]
# Baseline errors, and display average baseline error
#baseline_errors = abs(baseline_preds - test_labels)
#print('Average baseline error: ', round(np.mean(baseline_errors), 2))

In [112]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 100 decision trees
rf = RandomForestRegressor(n_estimators = 100, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [113]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 5), 'degrees.')

Mean Absolute Error: 0.01398 degrees.

In [114]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / test_labels)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 99.08 %.

In [115]:
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True, precision = 1)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')

In [116]:
# Get numerical feature importances
importances = list(rf.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: DepDelay             Importance: 0.7
Variable: ActualElapsedTime    Importance: 0.13
Variable: CRSElapsedTime       Importance: 0.13
Variable: DayofMonth           Importance: 0.01
Variable: ArrTime              Importance: 0.01
Variable: FlightNum            Importance: 0.01
Variable: Year                 Importance: 0.0
Variable: Month                Importance: 0.0
Variable: DayOfWeek            Importance: 0.0
Variable: DepTime              Importance: 0.0
Variable: CRSDepTime           Importance: 0.0
Variable: CRSArrTime           Importance: 0.0
Variable: Cancelled            Importance: 0.0
Variable: Diverted             Importance: 0.0

#### Some of this code was followed by a tutorial found on https://towardsdatascience.com/random-forest-in-python-24d0893d51c0